[package]
name = "almost_metal"
version = "0.1.0"
edition = "2021"

[dependencies]
bare-metal = "1.0.0"
libc = { version = "0.2.126", default-features = false }

[lints.rust]
unexpected_cfgs = { level = "allow" }

[profile.dev]
panic = "abort"
codegen-units = 1
linker-flavor = "ld.lld"

[profile.release]
panic = "abort"
target = "x86_64-unknown-linux-gnu"
linker-flavor = "ld.lld"

[profile.arm]
inherits = "dev"
target = "aarch64-unknown-linux-gnu"
panic = "abort"
linker-flavor = "ld.lld"

[[bin]]
name = "almost_metal"
path = "src/main.rs"
