[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bare-metal = "1.0.0"
exit-no-std = "0.2.1"

[profile.dev]
panic = "abort"
codegen-units = 1
linker-flavor = "ld.lld"

[profile.release]
panic = "abort"
linker-flavor = "ld.lld"

[[bin]]
name = "rust_project"
path = "src/main.rs"
